name: SpawnersFix
version: 1.0
description: Plugin do naprawy spawnerActivationRange ktory nie jest zmienialny w Bukkicie
author: Londek
main: pl.Londek.SpawnersFix.SpawnersFix
commands:
  spawnersfix:
    aliases: [sf, spawnerfix]